# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14968a66b82622e59bde0d42950d8053bb276e6c455f583f18b8ef4c3349fc97bb78058d2cb4f366242c5f891887254ad43d618c5aa898950eab116e22427051

test:
  secret_key_base: a6b2534ae3837ac794670fa9f717323c610f6472d2672ac27189fd33d1a9f334e14596e12f9efe05540777f5d4c69e12c3d27b8de677bbf2ccbd6393784a21c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
